# Generated by Django 5.0.2 on 2024-02-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('playerGameID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=200)),
                ('gameID', models.CharField(max_length=20)),
                ('queue', models.CharField(max_length=10)),
                ('placement', models.IntegerField()),
                ('level', models.IntegerField()),
                ('length', models.CharField(max_length=10)),
                ('round', models.CharField(max_length=10)),
                ('augments', models.CharField(max_length=100)),
                ('headliner', models.CharField(max_length=20)),
                ('traits', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=2)),
                ('tag', models.CharField(max_length=5)),
            ],
        ),
    ]
