# Generated by Django 5.0.2 on 2024-03-04 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_info',
            fields=[
                ('game_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=50)),
                ('lobby_rank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='patch',
            fields=[
                ('patch_id', models.FloatField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=2)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='game_unit',
            fields=[
                ('game_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('item', models.ManyToManyField(to='tft.item')),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.patch')),
            ],
        ),
        migrations.CreateModel(
            name='game_list',
            fields=[
                ('game_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.game_info')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.player')),
            ],
        ),
        migrations.AddField(
            model_name='game_info',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.player'),
        ),
        migrations.AddField(
            model_name='patch',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.set'),
        ),
        migrations.AddField(
            model_name='item',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.set'),
        ),
        migrations.CreateModel(
            name='augment',
            fields=[
                ('augment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.IntegerField()),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.set')),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('trait_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.set')),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('player_game_id', models.AutoField(primary_key=True, serialize=False)),
                ('placement', models.IntegerField()),
                ('level', models.IntegerField()),
                ('length', models.CharField(max_length=10)),
                ('round', models.CharField(max_length=10)),
                ('augment_id', models.ManyToManyField(to='tft.augment')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.game_info')),
                ('unit_id', models.ManyToManyField(to='tft.game_unit')),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.patch')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.player')),
                ('headliner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headliner', to='tft.trait')),
                ('trait_id', models.ManyToManyField(related_name='traits', to='tft.trait')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.IntegerField()),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.set')),
                ('trait', models.ManyToManyField(to='tft.trait')),
            ],
        ),
        migrations.AddField(
            model_name='game_unit',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.unit'),
        ),
    ]
