# Generated by Django 5.0.2 on 2024-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synergy',
            name='trait_id',
        ),
        migrations.AddField(
            model_name='trait',
            name='synergy',
            field=models.ManyToManyField(to='tft.synergy'),
        ),
    ]
