# Generated by Django 5.0.2 on 2024-03-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_info',
            name='player_id',
        ),
        migrations.AddField(
            model_name='game_info',
            name='player_id',
            field=models.ManyToManyField(to='tft.player'),
        ),
    ]
