# Generated by Django 5.0.2 on 2024-03-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_remove_synergy_trait_id_trait_synergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='synergy',
            name='name',
            field=models.CharField(default=int, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synergy',
            name='set_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='tft.set'),
            preserve_default=False,
        ),
    ]
