# Generated by Django 5.0.2 on 2024-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_remove_game_info_player_id_game_info_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
