# Generated by Django 5.0.2 on 2024-03-06 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0003_alter_set_set_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='revival_set_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='revival_set_id', to='tft.set'),
            preserve_default=False,
        ),
    ]
