# Generated by Django 5.0.2 on 2024-03-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0003_synergy_name_synergy_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='synergy',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
