# Generated by Django 5.0.2 on 2024-03-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0004_alter_augment_description_alter_synergy_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='description',
            new_name='ability_description',
        ),
        migrations.AddField(
            model_name='unit',
            name='ability_icon',
            field=models.CharField(default=int, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='ability_info',
            field=models.CharField(default=int, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='ability_name',
            field=models.CharField(default=int, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='stats',
            field=models.CharField(default=int, max_length=1000),
            preserve_default=False,
        ),
    ]
