# Generated by Django 5.0.2 on 2024-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0005_set_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trait_id',
            field=models.ManyToManyField(to='tft.trait'),
        ),
    ]
