# Generated by Django 5.0.2 on 2024-03-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0006_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_rank',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
