# Generated by Django 5.0.2 on 2024-03-06 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0006_alter_game_trait_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='unit_id',
            new_name='game_unit_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trait_id',
        ),
        migrations.CreateModel(
            name='game_trait',
            fields=[
                ('game_trait_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('trait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tft.trait')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_trait_id',
            field=models.ManyToManyField(to='tft.game_trait'),
        ),
    ]
