# Generated by Django 5.0.2 on 2024-03-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0007_player_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_lp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
