# Generated by Django 5.0.2 on 2024-03-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0007_rename_unit_id_game_game_unit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='headliner_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='headliner', to='tft.trait'),
        ),
    ]
