# Generated by Django 5.0.2 on 2024-03-19 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0008_player_player_lp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='patch_id',
        ),
        migrations.AddField(
            model_name='game_info',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_info',
            name='patch_id',
            field=models.ForeignKey(default=14.5, on_delete=django.db.models.deletion.CASCADE, to='tft.patch'),
            preserve_default=False,
        ),
    ]
