# Generated by Django 5.0.2 on 2024-03-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0009_remove_game_date_remove_game_patch_id_game_info_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='revival_set_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='revival_set_id', to='tft.set'),
        ),
    ]
