# Generated by Django 5.0.2 on 2024-03-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0009_alter_game_headliner_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game_list',
        ),
    ]
