# Generated by Django 5.0.2 on 2024-03-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0010_alter_patch_revival_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='revival_set_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revival_set_id', to='tft.set'),
        ),
    ]
