# Generated by Django 5.0.2 on 2024-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0011_alter_patch_revival_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
