# Generated by Django 5.0.2 on 2024-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0012_alter_augment_description_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='icon',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trait',
            name='icon',
            field=models.CharField(max_length=500),
        ),
    ]
