# Generated by Django 5.0.2 on 2024-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0013_alter_augment_icon_alter_item_icon_alter_trait_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='augment',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trait',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='augment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
