# Generated by Django 5.0.2 on 2024-03-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0014_augment_display_name_item_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
