# Generated by Django 5.0.2 on 2024-03-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0015_alter_augment_icon_alter_item_icon_alter_trait_icon_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game_info',
            index=models.Index(fields=['queue'], name='tft_game_in_queue_f586e4_idx'),
        ),
    ]
