# Generated by Django 5.0.2 on 2024-05-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0016_game_info_tft_game_in_queue_f586e4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
