# Generated by Django 5.0.2 on 2024-05-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0018_patch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
